const EventType = {
  /* LED */
  LED_ERROR: 'EVENT_TYPE/LED_ERROR',
  LED_OFF: 'EVENT_TYPE/LED_OFF',
  LED_ON: 'EVENT_TYPE/LED_ON',
  /* PID */
  PID_ERROR: 'EVENT_TYPE/PID_ERROR',
  PID_PARAMETERS_SET: 'EVENT_TYPE/PID_PARAMETERS_SET',
  PID_TARGET_SET: 'EVENT_TYPE/PID_TARGET_SET',
  PID_VALUE_CHANGED: 'EVENT_TYPE/PID_VALUE_CHANGED',
  /* pin */
  PIN_CLOSE: 'EVENT_TYPE/PIN_CLOSE',
  PIN_ERROR: 'EVENT_TYPE/PIN_ERROR',
  PIN_HIGH: 'EVENT_TYPE/PIN_HIGH',
  PIN_LOW: 'EVENT_TYPE/PIN_LOW',
  PIN_OPEN: 'EVENT_TYPE/PIN_OPEN',
  PIN_READ: 'EVENT_TYPE/PIN_READ',
  /* relay */
  RELAY_ERROR: 'EVENT_TYPE/RELAY_ERROR',
  RELAY_OFF: 'EVENT_TYPE/RELAY_OFF',
  RELAY_ON: 'EVENT_TYPE/RELAY_ON',
  /* thermometer */
  THERMOMETER_ERROR: 'EVENT_TYPE/THERMOMETER_ERROR',
  THERMOMETER_INITIALIZED: 'EVENT_TYPE/THERMOMETER_INITIALIZED',
  THERMOMETER_READ: 'EVENT_TYPE/THERMOMETER_READ',
};

module.exports = {
  EventType,
};
