const LEDColor = {
  BLUE: 'LED_COLOR/BLUE',
  GREEN: 'LED_COLOR/GREEN',
  RED: 'LED_COLOR/RED',
  YELLOW: 'LED_COLOR/YELLOW',
};

const PIDParams = {
  PROPORTIONAL_GAIN: 'PID/PROPORTIONAL_GAIN',
  INTEGRAL_GAIN: 'PID/INTEGRAL_GAIN',
  DERIVATIVE_GAIN: 'PID/DERIVATIVE_GAIN',
  MAX_INTEGRAL: 'PID/MAX_INTEGRAL',
};

const PIDState = {
  UNINITIALIZED: 'PID_STATE/UNINITIALIZED',
  READY: 'PID_STATE/READY',
  ON: 'PID_STATE/ON',
  OFF: 'PID_STATE/OFF',
  ERROR: 'PID_STATE/ERROR',
};

const PinState = {
  INITIALIZED: 'PIN_STATE/INITIALIZED',
  CLOSED: 'PIN_STATE/CLOSED',
  HIGH: 'PIN_STATE/HIGH',
  LOW: 'PIN_STATE/LOW',
};

module.exports = {
  LEDColor,
  PIDParams,
  PIDState,
  PinState,
};
